name: RailBar
options:
  bundleIdPrefix: com.michalcerny
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  RailBar:
    type: application
    platform: macOS
    sources:
      - RailBar
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.michalcerny.RailBar
        PRODUCT_NAME: RailBar
        INFOPLIST_FILE: RailBar/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_HARDENED_RUNTIME: true
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Automatic
        COMBINE_HIDPI_IMAGES: true
    info:
      path: RailBar/Info.plist
      properties:
        CFBundleName: RailBar
        CFBundleDisplayName: RailBar
        CFBundleIdentifier: com.michalcerny.RailBar
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: RailBar
        LSMinimumSystemVersion: "14.0"
        LSUIElement: true
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
