name: RailwayBar
options:
  bundleIdPrefix: com.michalcerny
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  RailwayBar:
    type: application
    platform: macOS
    sources:
      - RailwayBar
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.michalcerny.RailwayBar
        PRODUCT_NAME: RailwayBar
        INFOPLIST_FILE: RailwayBar/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_HARDENED_RUNTIME: true
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Automatic
        COMBINE_HIDPI_IMAGES: true
    info:
      path: RailwayBar/Info.plist
      properties:
        CFBundleName: RailwayBar
        CFBundleDisplayName: Railway Bar
        CFBundleIdentifier: com.michalcerny.RailwayBar
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: RailwayBar
        LSMinimumSystemVersion: "14.0"
        LSUIElement: true
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
